language: python
python:
  - "2.7"
env:
 global:
  - DJANGO="1.5.5"
 matrix:
  - INTERFACE="1"
install:
  - pip install -r requirements.txt
  - pip install coveralls --use-mirrors
script:
  coverage run --source=django django/mysite/manage.py test polls
after_success:
  coveralls
