language: python
python:
  - "2.7"
env:
  # - DJANGO=1.2.7
  # - DJANGO=1.3.1
  - DJANGO=1.5.5 
install:
  - pip install -r requirements.txt
  - pip install coveralls --use-mirrors
script:
  coverage run --source=moscowdjango,meetup django/mysite/manage.py test polls
after_success:
  coveralls
  